base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/winequality.csv  #source of data

load_data:
  raw_dataset_csv: data/raw/winequality.csv  #putting the src data into raw data 

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv             #Train test split
  test_size: 0.2

estimators:   #ML Algorithm (Regression) 
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.92
      l1_ratio: 0.46
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib